

##服务器配置
server:
  port: 8080

##日志
logging:
   level:
      com.lsp: INFO
   file: ./log/server.log

##soring配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 15160079202stra
    type: com.alibaba.druid.pool.DruidDataSource
  #前端模版引擎
  thymleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
     
    
## mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lsp.oct.entity  # 注意：对应实体类的路径
    
    
## pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

##thymeleaf 前度模板引擎

   
    
 